import { useState } from 'react';
import { useApp } from '../app/context';
import { api } from '../api/client';
import { useQuery } from '../api/query';
import type { Property, Person, CheckItem } from '../domain/models';
import { changedFields, parseMoney } from '../domain/rules.mjs';
import { Header, Button, Icon, QueryState, Empty, Badge, Modal, Form, options, type Field } from '../ui/components';
export function Properties() { const { user, t, money } = useApp(), operator = ['ADMIN', 'OPERATIONS_MANAGER'].includes(user!.role), prefix = operator ? 'admin' : 'client'; const q = useQuery<{
    objects: Property[];
}>(`${prefix}/objects`), [search, setSearch] = useState(''), [editing, setEditing] = useState<Property | 'new' | null>(null), [checklist, setChecklist] = useState<Property | null>(null); const rows = q.data?.objects.filter(o => `${o.name} ${o.address}`.toLowerCase().includes(search.toLowerCase())) || []; return <><Header title="Properties">{user!.role !== 'PROPERTY_MANAGER' && <Button kind="primary" onClick={() => setEditing('new')}><Icon name="plus"/>{t('New property')}</Button>}</Header><div className="toolbar"><div className="search"><Icon name="search"/><input aria-label={t('Search')} placeholder={t('Search')} value={search} onChange={e => setSearch(e.target.value)}/></div></div><QueryState {...q} retry={q.reload}>{rows.length ? <div className="property-grid">{rows.map(o => <article className="property-card" key={o.id}><div className="property-top"><div className="property-icon"><Icon name="properties" size={27}/></div><Badge value={o.approval_status}/></div><span className="eyebrow">{o.code} · {o.zone}</span><h3>{o.name}</h3><p>{o.address}</p><div className="property-facts"><span>{o.checkout_time?.slice(0, 5)} — {o.deadline_time?.slice(0, 5)}</span><span>{o.duration_minutes} {t('minutes')}</span>{o.client_price !== undefined && <span>{money(Number(o.client_price))}</span>}</div><div className="actions"><Button onClick={() => setEditing(o)}>{t('Edit')}</Button>{operator && <Button onClick={() => setChecklist(o)}>{t('Checklist')}</Button>}</div></article>)}</div> : <Empty />}</QueryState>{editing && <Modal title={editing === 'new' ? 'New property' : 'Edit'} onClose={() => setEditing(null)}><PropertyForm property={editing === 'new' ? undefined : editing} prefix={prefix} onDone={() => setEditing(null)}/></Modal>}{checklist && <Modal title={`${t('Checklist')} · ${checklist.name}`} onClose={() => setChecklist(null)}><ChecklistEditor property={checklist}/></Modal>}</>; }
function PropertyForm({ property, prefix, onDone }: {
    property?: Property;
    prefix: string;
    onDone: () => void;
}) { const { t, user } = useApp(), operator = prefix === 'admin', finance = user!.role === 'ADMIN'; const clients = useQuery<{
    clients: Person[];
}>(operator ? 'admin/clients' : null); const fields: Field[] = [{ name: 'name', label: 'Name', required: true }, { name: 'address', label: 'Address', required: true, wide: true }, { name: 'zone', label: 'Zone', required: true }, { name: 'serviceCategory', label: 'Category', options: options(['SHORT_STAY', 'HOME', 'OFFICE', 'COMMON_AREAS', 'OTHER'], t) }, { name: 'bedrooms', label: 'Bedrooms', type: 'number', min: 0 }, { name: 'bathrooms', label: 'Bathrooms', type: 'number', min: 0 }, { name: 'lat', label: 'Latitude' }, { name: 'lng', label: 'Longitude' }, ...(operator ? [{ name: 'clientId', label: 'Client', options: clients.data?.clients.filter(c => c.account_type === 'OWNER').map(c => ({ value: c.id, label: c.full_name || c.company_name || c.email })) || [] }, { name: 'approvalStatus', label: 'Approval', options: options(['APPROVED', 'PENDING', 'REJECTED'], t) }, { name: 'checkoutTime', label: 'Start', type: 'time', required: true }, { name: 'deadlineTime', label: 'Deadline', type: 'time', required: true }, { name: 'durationMinutes', label: 'Duration', type: 'number', min: 15, required: true }, ...(finance ? [{ name: 'clientPrice', label: 'Client price', required: true }] : []), { name: 'payout', label: 'Payout', required: true }, { name: 'active', label: 'Active', type: 'checkbox' }] : []), ...[['accessInstructions', 'Access instructions'], ['keyInstructions', 'Keys'], ['parking', 'Parking'], ['linenLocation', 'Linen'], ['suppliesLocation', 'Supplies'], ['notes', 'Notes']].map(([name, label]) => ({ name, label, type: 'textarea', wide: true }))]; const initial: Record<string, unknown> = { zone: 'Bratislava', serviceCategory: 'SHORT_STAY', bedrooms: 1, bathrooms: 1, checkoutTime: '10:00', deadlineTime: '15:00', durationMinutes: 120, clientPrice: 0, payout: 0, approvalStatus: 'APPROVED', active: true }; if (property)
    for (const f of fields)
        initial[f.name] = (property as unknown as Record<string, unknown>)[f.name.replace(/[A-Z]/g, c => '_' + c.toLowerCase())] ?? ''; return <Form fields={fields} initial={initial} onCancel={onDone} onSubmit={async (v) => { const body: Record<string, unknown> = { ...v }; for (const k of ['bedrooms', 'bathrooms', 'durationMinutes'])
    if (k in body)
        body[k] = Number(body[k]); for (const k of ['clientPrice', 'payout'])
    if (k in body)
        body[k] = parseMoney(body[k]) / 100; for (const k of ['lat', 'lng'])
    body[k] = String(body[k]).trim() ? Number(String(body[k]).replace(',', '.')) : null; if ((body.lat == null) !== (body.lng == null) || body.lat !== null && (!Number.isFinite(body.lat) || Number(body.lat) < -90 || Number(body.lat) > 90) || body.lng !== null && (!Number.isFinite(body.lng) || Number(body.lng) < -180 || Number(body.lng) > 180))
    throw new Error(t('Invalid coordinates')); if ('clientId' in body)
    body.clientId = body.clientId ? Number(body.clientId) : null; await api(`${prefix}/objects${property ? `/${property.id}` : ''}`, { method: property ? 'PATCH' : 'POST', body: property ? changedFields(property, body) : body }); onDone(); }}/>; }
function ChecklistEditor({ property }: {
    property: Property;
}) { const q = useQuery<{
    items: CheckItem[];
}>(`admin/objects/${property.id}/checklist`); return <QueryState {...q} retry={q.reload}>{q.data && <ChecklistDraft property={property} initial={q.data.items}/>}</QueryState>; }
function ChecklistDraft({ property, initial }: {
    property: Property;
    initial: CheckItem[];
}) { const { t } = useApp(), [items, setItems] = useState(initial.map(i => ({ label: i.label, required: i.required, photoRequired: i.photo_required, photoCategory: i.photo_category || 'Final' }))); return <div className="checklist-editor">{items.map((item, index) => <div className="checklist-edit-row" key={index}><input aria-label={t('Description')} value={item.label} onChange={e => setItems(items.map((v, i) => i === index ? { ...v, label: e.target.value } : v))}/><label><input type="checkbox" checked={item.required} onChange={e => setItems(items.map((v, i) => i === index ? { ...v, required: e.target.checked } : v))}/>{t('Required')}</label><label><input type="checkbox" checked={item.photoRequired} onChange={e => setItems(items.map((v, i) => i === index ? { ...v, photoRequired: e.target.checked } : v))}/>{t('Photo report')}</label>{item.photoRequired && <input aria-label={t('Category')} value={item.photoCategory} onChange={e => setItems(items.map((v, i) => i === index ? { ...v, photoCategory: e.target.value } : v))}/>}<Button kind="icon" aria-label={t('Delete')} onClick={() => setItems(items.filter((_, i) => i !== index))}><Icon name="close"/></Button></div>)}<Button onClick={() => setItems([...items, { label: '', required: true, photoRequired: false, photoCategory: 'Final' }])}><Icon name="plus"/>{t('Add')}</Button><Form fields={[]} onSubmit={() => { if (items.some(i => !i.label.trim() || i.photoRequired && !i.photoCategory.trim()))
    throw new Error(t('Required')); return api(`admin/objects/${property.id}/checklist`, { method: 'PUT', body: { items } }); }}/></div>; }
