import { useState } from 'react';
import { useApp } from '../app/context';
import { api } from '../api/client';
import { useQuery } from '../api/query';
import { serviceToday } from '../domain/rules.mjs';
import type { Schedule, Property } from '../domain/models';
import { Header, Button, Icon, QueryState, Empty, Modal, Form, Action } from '../ui/components';
export function Recurring() { const { t, language } = useApp(), q = useQuery<{
    schedules: Schedule[];
}>('admin/recurring'), objects = useQuery<{
    objects: Property[];
}>('admin/objects'), [creating, setCreating] = useState(false), [generating, setGenerating] = useState<Schedule | null>(null), [days, setDays] = useState([1, 3, 5]); const weekdays = Array.from({ length: 7 }, (_, i) => new Intl.DateTimeFormat(language, { weekday: 'short' }).format(new Date(2026, 8, 7 + i))); return <><Header title="Recurring cleaning"><Button kind="primary" onClick={() => setCreating(true)}><Icon name="plus"/>{t('New schedule')}</Button></Header><QueryState {...q} retry={q.reload}>{q.data?.schedules.length ? <div className="property-grid">{q.data.schedules.map(s => <article className="property-card" key={s.id}><span className="eyebrow">{s.st_objects?.code}</span><h3>{s.st_objects?.name}</h3><p>{s.start_date} → {s.end_date || '∞'} · {s.planned_start.slice(0, 5)}</p><div className="weekdays">{weekdays.map((d, i) => <span className={s.weekdays.includes(i + 1) ? 'selected' : ''} key={i}>{d}</span>)}</div><div className="actions"><Action label={s.active ? 'Pause' : 'Resume'} onClick={() => api(`admin/recurring/${s.id}`, { method: 'PATCH', body: { active: !s.active } })}/><Button onClick={() => setGenerating(s)}>{t('Generate through date')}</Button></div></article>)}</div> : <Empty />}</QueryState>{creating && <Modal title="New schedule" onClose={() => setCreating(false)}><QueryState {...objects} retry={objects.reload}><fieldset className="weekdays"><legend>{t('Weekdays')}</legend>{weekdays.map((d, i) => <label key={i}><input type="checkbox" checked={days.includes(i + 1)} onChange={e => setDays(e.target.checked ? [...days, i + 1] : days.filter(x => x !== i + 1))}/>{d}</label>)}</fieldset><Form fields={[{ name: 'objectId', label: 'Object', required: true, options: objects.data?.objects.filter(o => o.active && o.approval_status === 'APPROVED').map(o => ({ value: o.id, label: o.name })) || [] }, { name: 'startDate', label: 'Date', type: 'date', required: true }, { name: 'endDate', label: 'End', type: 'date' }, { name: 'plannedStart', label: 'Start', type: 'time', required: true }]} initial={{ startDate: serviceToday(), plannedStart: '10:00' }} onSubmit={async (v) => { if (!days.length)
    throw new Error(t('Weekdays')); await api('admin/recurring', { method: 'POST', body: { ...v, objectId: Number(v.objectId), weekdays: days } }); setCreating(false); }}/></QueryState></Modal>}{generating && <Modal title="Generate through date" onClose={() => setGenerating(null)}><Form fields={[{ name: 'until', label: 'Date', type: 'date', required: true }]} initial={{ until: serviceToday() }} onSubmit={async (v) => { await api(`admin/recurring/${generating.id}/generate`, { method: 'POST', body: v }); setGenerating(null); }}/></Modal>}</>; }
